### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Vickymsg** [DavidSegura182/Mercado-Liebre#1]
- [ ] 1 - Falta "Sección de ofertas" en Main
- [x] 2 - Cumple
- [x] 3 - Cumple 
- [x] 4 - Cumple
- [x] 5 - Cumple
- [x] 6 - Cumple
- [x] 7 - Cumple
- [x] 8 - Cumple
- [x] 9 - En general creo que es una buena pagina y cumple con los puntos requeridos :)
- [ ] 10 - Creo que lo unico que podria mejorar es los hover dentro de los productos no tener tantas animaciones para que no se vean sombras sobre sombras en la card ya que es el mismo producto

**Comment by DavidSegura182** [comment]
Se agregó la Sección de ofertas en main, se ajusto las opiniones del punto 10
