### ISSUE TITLE
Peer Review- MercadoLiebre

### ISSUE THREAD

**Issue by sorrego98** [DavidSegura182/Mercado-Liebre#2]
- [ ] 1.  **NO CUMPLE**: La sección Main no cuenta con el apartado **_OFERTAS_**.
- [ ] 2. **NO CUMPLE**: No pude apreciar un margen inferior de 10 px de separación en los íconos.
- [x] 3. **CUMPLE**: La página se adapta a diferentes resoluciones.
- [x] 4. **CUMPLE**: La página cuenta con un formulario de registro.
- [x] 5. **CUMPLE**: La página cuenta con un formulario de login.
- [x] 6. **CUMPLE**: Se muestra un mensaje de error al llenar mal el formulario de un campo.
- [x] 7. **CUMPLE**: El _Search Bar_ corresponde a un formulario.
- [x] 8. **CUMPLE**: Se cuenta con transiciones y animaciones de _CSS_.
- [x] 9. Me gustó como quedó el diseño y organización del _Header_ y el formulario del _Login_.
- [ ] 10.  Centrar los elementos del formulario del _Registro_ y hacer las transiciones de los camiones de envío un poco más lentas.

**Comment by DavidSegura182** [comment]
Ya agregué la sección Main Ofertas, se ajustaron los tamaños del margen. Se ajustaron los elementos del formulario de registro.
